(() => {
const $=id=>document.getElementById(id);
let rows=[],period="30";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const val=(r,k)=>r[k]===undefined||r[k]===""?"不明":r[k];
const date=r=>{const d=new Date(r.timestamp||r.receivedAt);return isNaN(d)?null:d};
function filtered(){if(period==="all")return rows;const limit=Date.now()-(period==="today"?1:Number(period))*86400000;return rows.filter(r=>date(r)&&date(r).getTime()>=limit)}
function counts(list,key){const m={};list.forEach(r=>{const k=val(r,key);m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function list(id,items){const el=$(id);el.innerHTML="";if(!items.length){el.innerHTML='<p class="empty">データがありません</p>';return}const max=items[0][1];items.slice(0,10).forEach(([name,n])=>{el.insertAdjacentHTML("beforeend",`<div class="rank"><div class="rank-top"><span>${esc(name)}</span><b>${n}</b></div><div class="track"><div class="fill" style="width:${n/max*100}%"></div></div></div>`)})}
function render(){const listRows=filtered();$("pv").textContent=listRows.length.toLocaleString();$("users").textContent=new Set(listRows.map(r=>r.userId).filter(Boolean)).size.toLocaleString();$("sessions").textContent=new Set(listRows.map(r=>r.sessionId).filter(Boolean)).size.toLocaleString();$("newUsers").textContent=listRows.filter(r=>String(r.isNewUser).toLowerCase()==="true").length.toLocaleString();list("pages",counts(listRows,"page"));list("sources",counts(listRows,"source"));list("devices",counts(listRows,"device"));$("details").innerHTML=listRows.slice().reverse().slice(0,100).map(r=>`<tr><td>${date(r)?date(r).toLocaleString("ja-JP"):"不明"}</td><td>${esc(val(r,"page"))}</td><td>${esc(val(r,"source"))}</td><td>${esc(val(r,"device"))}</td></tr>`).join("");$("status").textContent=`${listRows.length}件を表示中`}
async function load(){ $("status").textContent="読み込み中…";try{const url=`${ANALYTICS_CONFIG.gasUrl}?action=analytics&key=${encodeURIComponent(ANALYTICS_CONFIG.apiKey)}`;const res=await fetch(url);if(!res.ok)throw Error("HTTP "+res.status);const data=await res.json();rows=data.rows||data.data||data; if(!Array.isArray(rows))throw Error("データ形式が不正です");render()}catch(e){console.error(e);$("status").textContent="取得できません。GASの公開設定・URL・CORSを確認してください。"}}
$("period").addEventListener("change",e=>{period=e.target.value;render()});$("reload").addEventListener("click",load);load();
})();